# -*- coding: utf-8 -*-
"""Project_confirm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17XapzvHCj1DSqzuC5P_HgB53wj3eFWZh
"""



# Commented out IPython magic to ensure Python compatibility.
import os
import cv2
import pafy
import math
import random
import numpy as np
import datetime as dt
import tensorflow as tf
from collections import deque
import matplotlib.pyplot as plt

from moviepy.editor import *
# %matplotlib inline

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from tensorflow.keras.layers import *
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical, plot_model
from tensorflow.keras.callbacks import EarlyStopping

"""Contol the randomness"""

seed_constant = 27
np.random.seed(seed_constant)
random.seed(seed_constant)
tf.random.set_seed(seed_constant)

#Download the UCF50 Dataset
!wget --no-check-certificate https://www.crcv.ucf.edu/data/UCF50.rar

#Exctract dataset
!unrar x UCF50.rar

#Creating a Matplotlib figure and specify the size of the figure
plt.figure(figsize = (20,20))

#Get names of all classes
all_classes_names = os.listdir('UCF50')

#Generate a list of 20 random values between 0-50
#50->total number of classes
random_range = random.sample(range(len(all_classes_names)), 40)

for count, rand_idx in enumerate(random_range, 1):

  #retrieve a class name using random index
  sel_class_name = all_classes_names[rand_idx]

  #retrieve a list all video  from the selected class
  vid_file_name = os.listdir(f'UCF50/{sel_class_name}')

  #retrieve a video randomly from the video list
  sel_vid_name = random.choice(vid_file_name)

  #Initialize VideoCapture Object to read from the selected vide file
  vid_read = cv2.VideoCapture(f'UCF50/{sel_class_name}/{sel_vid_name}')

  #Read the first frame of the video
  _, bgr_frame = vid_read.read()

  #Release the videocapture object
  vid_read.release()

  #Converting Background frames to RGB frames
  rgb_frame = cv2.cvtColor(bgr_frame, cv2.COLOR_BGR2RGB)

  #Write the classname on the video frame
  cv2.putText(rgb_frame, sel_class_name, (10,30), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2)

  #Display the frame
  plt.subplot(5, 8, count);plt.imshow(rgb_frame);plt.axis('off')

IMAGE_HEIGHT, IMAGE_WIDTH = 64, 64

SEQUENCE_LENGTH = 20

DATASET_DIR = 'UCF50'

CLASSES_LIST = ["TaiChi", "Punch", "Nunchucks", "Fencing"]

def frames_extraction(video_path):
  '''
  This function will extract required frames from the video after resizing and normalizing them.
  Args:
    video_path: The path of the  video in the disk, whose frames are to be extracted.
  Returns:
    frames_list: A list containing the resized  and normalized frame of the video
  '''

  #Declaring frame list
  frame_list = []

  #Read the video using Video Capture object
  video_read = cv2.VideoCapture(video_path)

  #Counts the frmaes in the video
  vid_frame_count = int(video_read.get(cv2.CAP_PROP_FRAME_COUNT))

  #Calculates the interval after which frames will be added to the list
  sk_frame_count = max(int(vid_frame_count/SEQUENCE_LENGTH), 1)

  for frame_count in range(SEQUENCE_LENGTH):

    #Set current frame position of the video
    video_read.set(cv2.CAP_PROP_POS_FRAMES, frame_count * sk_frame_count)

    #Reading frame from the video
    success, frame = video_read.read()

    #Check if the video u=is not successfuly read
    if not success:
      break

    #Resize the frame
    resized_frame = cv2.resize(frame, (IMAGE_HEIGHT, IMAGE_WIDTH))

    #Normalize the frame by dividing it with 255 so that each pixel calue lies between 0 and 1
    normalized_frame = resized_frame/255

    #append the normalized frame to the frame list
    frame_list.append(normalized_frame)

  #Release the VidoeCapture Object
  video_read.release()

  return frame_list

def create_dataset():
  '''
  This function will extract the data from the selected class and create the required dataset
  Returns:
    features:         A list containing the extracted frames of the videos
    labels:           A list containing the indexes of the classes associated the videos
    vidoe_file_path:  A list containing the paths of the videos in the disk.
  '''

  #Createing the empty list
  features = []
  labels = []
  video_file_path = []

  for class_index, clas_name in enumerate(CLASSES_LIST):

    print(f'Extracting data of class: {clas_name}')

    #Get list of video files present in the specific class name directory.
    files_list = os.listdir(os.path.join(DATASET_DIR, clas_name))

    for file_name in files_list:

      #Get full vidoe path
      video_file_paths = os.path.join(DATASET_DIR, clas_name, file_name)

      #Exctract the frames from the video file
      frames = frames_extraction(video_file_paths)

      #Check if the extracted frames is equl to Sequece length
      #Ignore the video having frames less than Sequence Length
      if len(frames) == SEQUENCE_LENGTH:

        #Append the data according to the list created
        features.append(frames)
        labels.append(class_index)
        video_file_path.append(video_file_paths)

  features = np.asarray(features)
  labels = np.array(labels)

  return features, labels, video_file_path

features, labels, video_files_paths = create_dataset()

one_hot_encoded_labels = to_categorical(labels)

features_train, features_test, labels_tarin, labels_test = train_test_split(features, one_hot_encoded_labels, test_size=0.25, shuffle = True, random_state = seed_constant)

print("Features type:", type(features))
print("Labels type:", type(labels))
print("Features shape:", features.shape if hasattr(features, "shape") else "No shape attribute")
print("Labels shape:", labels.shape if hasattr(labels, "shape") else "No shape attribute")
print("Unique labels:", set(labels) if hasattr(labels, "__iter__") else "Not iterable")

# Flatten the features
num_samples = features.shape[0]
flattened_features = features.reshape(num_samples, -1)  # Converts to (521, 20*64*64*3)

# Split the dataset
features_train, features_test, labels_train, labels_test = train_test_split(
    flattened_features, labels, test_size=0.25, random_state=42, shuffle=True
)

# Train the Random Forest model
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(features_train, labels_train)

# Make predictions
predictions = rf_classifier.predict(features_test)

# Evaluate the model
accuracy = accuracy_score(labels_test, predictions)
print(f"Random Forest Accuracy: {accuracy:.2f}")

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from sklearn.model_selection import train_test_split

# Repeat labels to match the number of frames
labels_expanded = np.repeat(labels, 20)  # Each video label is repeated for 20 frames

# Verify shape consistency
print("X_cnn shape:", X_cnn.shape)  # (10420, 64, 64, 3)
print("Updated labels shape:", labels_expanded.shape)  # (10420,)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X_cnn, labels_expanded, test_size=0.25, random_state=42, shuffle=True
)

# Define CNN Model
cnn_model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(64, 64, 3)),
    MaxPooling2D(pool_size=(2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(pool_size=(2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(len(set(labels)), activation='softmax')  # Output layer for classification
])

# Compile model
cnn_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train model
cnn_model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

# Evaluate model
cnn_accuracy = cnn_model.evaluate(X_test, y_test)[1]
print(f"CNN Accuracy: {cnn_accuracy:.2f}")

from tensorflow.keras.layers import LSTM

# Reshape for LSTM: (samples, timesteps, features)
X_lstm = features.reshape(features.shape[0], features.shape[1], -1)  # (521, 20, 64*64*3)

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X_lstm, labels, test_size=0.25, random_state=42, shuffle=True)

# Define LSTM Model
lstm_model = Sequential([
    LSTM(64, return_sequences=True, input_shape=(20, 64*64*3)),
    LSTM(32),
    Dense(128, activation='relu'),
    Dense(len(set(labels)), activation='softmax')
])

# Compile & Train
lstm_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
lstm_model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

# Evaluate
lstm_accuracy = lstm_model.evaluate(X_test, y_test)[1]
print(f"LSTM Accuracy: {lstm_accuracy:.2f}")

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, TimeDistributed, LSTM, Flatten, Dense
from sklearn.model_selection import train_test_split

# Reshape for CNN+LSTM: (samples, timesteps, height, width, channels)
X_cnn_lstm = features  # Already in (521, 20, 64, 64, 3)

# Repeat labels for sequence-based learning (each video has 1 label)
y_cnn_lstm = labels  # No need to repeat since LSTM works per video sequence

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_cnn_lstm, y_cnn_lstm, test_size=0.25, random_state=42, shuffle=True
)

# Define CNN + LSTM model
cnn_lstm_model = Sequential([
    # Apply CNN to each frame using TimeDistributed
    TimeDistributed(Conv2D(32, (3, 3), activation='relu', padding='same'), input_shape=(20, 64, 64, 3)),
    TimeDistributed(MaxPooling2D(pool_size=(2, 2))),
    TimeDistributed(Conv2D(64, (3, 3), activation='relu', padding='same')),
    TimeDistributed(MaxPooling2D(pool_size=(2, 2))),
    TimeDistributed(Flatten()),  # Flatten feature maps per frame

    # LSTM layer for temporal learning
    LSTM(64, return_sequences=False),  # Output single vector per sequence
    Dense(128, activation='relu'),
    Dense(len(set(labels)), activation='softmax')  # Final output layer
])

# Compile model
cnn_lstm_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train model
cnn_lstm_model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

# Evaluate model
cnn_lstm_accuracy = cnn_lstm_model.evaluate(X_test, y_test)[1]
print(f"CNN + LSTM Accuracy: {cnn_lstm_accuracy:.2f}")

"""ConvLSTM Approach... Convolutional LSTM Approach"""

def create_convlstm_model():
  '''
  This function will construct the required convlstm model
  Returns:
    model: It is required constructed convlstm model.
  '''

  #We will use sequential model for model comstruction
  model = Sequential()

  #Define model Architecture

  model.add(ConvLSTM2D(filters = 4, kernel_size = (3,3), activation = 'tanh', data_format = "channels_last", recurrent_dropout = 0.2, return_sequences = True, input_shape = (SEQUENCE_LENGTH, IMAGE_HEIGHT, IMAGE_WIDTH, 3)))

  model.add(MaxPooling3D(pool_size = (1,2,2), padding = 'same', data_format = 'channels_last'))

  model.add(TimeDistributed(Dropout(0.2)))

  model.add(ConvLSTM2D(filters = 8, kernel_size = (3,3), activation = 'tanh',  data_format = "channels_last", recurrent_dropout = 0.2, return_sequences = True))

  model.add(MaxPool3D(pool_size = (1,2,2), padding = 'same', data_format = 'channels_last'))

  model.add(TimeDistributed(Dropout(0.2)))

  model.add(ConvLSTM2D(filters = 14, kernel_size = (3,3), activation = 'tanh',  data_format = "channels_last", recurrent_dropout = 0.2, return_sequences = True))

  model.add(MaxPool3D(pool_size = (1,2,2), padding = 'same', data_format = 'channels_last'))

  model.add(TimeDistributed(Dropout(0.2)))

  model.add(ConvLSTM2D(filters = 16, kernel_size = (3,3), activation = 'tanh',  data_format = "channels_last", recurrent_dropout = 0.2, return_sequences = True))

  model.add(MaxPool3D(pool_size = (1,2,2), padding = 'same', data_format = 'channels_last'))

  #model.add(TimeDistributed(Dropout(0.2)))

  model.add(Flatten())

  model.add(Dense(len(CLASSES_LIST), activation = "softmax"))

  #############################################################################################

  #Display Model summary
  model.summary()

  #Return Constructed ConvLSTM model
  return model

convlstm_model = create_convlstm_model()

print("Model Created Successfully")

"""Check Model Structure"""

#Plot the structure of the constructed model
plot_model(convlstm_model, to_file = 'convlstm_model_structure_plot.png', show_shapes = True, show_layer_names = True)

"""Compile and Train the Model"""

#Create an Instance of Early Stopping call back
early_stopping_callback = EarlyStopping(monitor = 'val_loss', patience = 10, mode = 'min', restore_best_weights = True)

#Compile model
convlstm_model.compile(loss = 'categorical_crossentropy', optimizer = 'Adam', metrics = ["accuracy"])

#Start training model
convlstm_model_training_history = convlstm_model.fit(x = features_train, y = labels_tarin, epochs = 50, batch_size = 4, shuffle = True, validation_split = 0.2, callbacks = [early_stopping_callback])

model_evalution_history = convlstm_model.evaluate(features_test, labels_test)

"""Save the model"""

model_evaluation_loss, model_evaluation_accuracy = model_evalution_history

date_time_format = '%Y_%m_%d_%H_%M_%S'
current_date_time_dt = dt.datetime.now()
current_date_time_string = dt.datetime.strftime(current_date_time_dt, date_time_format)

model_file_name = f'convlstm_model__Date_Time_{current_date_time_string}__Loss_{model_evaluation_loss}__Accuracy_{model_evaluation_accuracy}.h5'

convlstm_model.save(model_file_name)

def plot_metric(model_training_history, metric_name_1, metric_name_2, plot_name):
  '''
  This function will plot the metrics passed to it in graph.
  Args:
    model_training_history: A history object containing a record of training and validation loss values and metrics value at successive epochs
    metric_name_1:          The name of the first metric that needs to be plotted in the graph .
    metric_name_2:          The name of the first metric that needs to be plotted in the graph .
    plot_name:              The title of the graph.
  '''

  metric_value_1 = model_training_history.history[metric_name_1]
  metric_value_2 = model_training_history.history[metric_name_2]

  epochs = range(len(metric_value_1))

  plt.plot(epochs, metric_value_1, 'blue', label = metric_name_1)
  plt.plot(epochs, metric_value_2, 'red', label = metric_name_2)

  plt.title(str(plot_name))

  plt.legend()

plot_metric(convlstm_model_training_history, 'loss', 'val_loss', 'Total Loss vs Total Validation Loss')

plot_metric(convlstm_model_training_history, 'accuracy', 'val_accuracy', 'Total Accuracy vs Total Validation Accuracy')

"""LRCN Approach... CNN + LSTM approach"""

def create_LRCN_model():
  '''
  This function will contruct required LRCN model
  Returns:
      model:  It is the required constructed LRCN model
  '''

  model = Sequential()

  #Define Model Architecture

  model.add(TimeDistributed(Conv2D(16, (3,3), padding = 'same', activation = 'relu'), input_shape = (SEQUENCE_LENGTH, IMAGE_HEIGHT, IMAGE_WIDTH, 3)))
  model.add(TimeDistributed(MaxPooling2D((4,4))))
  model.add(TimeDistributed(Dropout(0.25)))

  model.add(TimeDistributed(Conv2D(32, (3,3), padding = 'same', activation = 'relu')))
  model.add(TimeDistributed(MaxPooling2D((4,4))))
  model.add(TimeDistributed(Dropout(0.25)))

  model.add(TimeDistributed(Conv2D(64, (3,3), padding = 'same', activation = 'relu')))
  model.add(TimeDistributed(MaxPooling2D((2,2))))
  model.add(TimeDistributed(Dropout(0.25)))

  model.add(TimeDistributed(Conv2D(64, (3,3), padding = 'same', activation = 'relu')))
  model.add(TimeDistributed(MaxPooling2D((2,2))))
  #model.add(TimeDistributed(Dropout(0.25)))

  model.add(TimeDistributed(Flatten()))

  model.add(LSTM(32))

  model.add(Dense(len(CLASSES_LIST), activation = 'softmax'))

  ################################################################################

  model.summary()

  return model

LRCN_model = create_LRCN_model()

print("Model Created Successully")

"""Check model Structure"""

plot_model(LRCN_model, to_file = 'LRCN_model_structure_plot.png', show_shapes = True, show_layer_names = True)

#Create an Instance of Early Stopping call back
early_stopping_callback = EarlyStopping(monitor = 'val_loss', patience = 15, mode = 'min', restore_best_weights = True)

#Compile model
LRCN_model.compile(loss = 'categorical_crossentropy', optimizer = 'Adam', metrics = ["accuracy"])

#Start training model
LRCN_model_training_history = LRCN_model.fit(x = features_train, y = labels_tarin, epochs = 70, batch_size = 4, shuffle = True, validation_split = 0.2, callbacks = [early_stopping_callback])

model_evalution_history = LRCN_model.evaluate(features_test, labels_test)

model_evaluation_loss, model_evaluation_accuracy = model_evalution_history

date_time_format = '%Y_%m_%d_%H_%M_%S'
current_date_time_dt = dt.datetime.now()
current_date_time_string = dt.datetime.strftime(current_date_time_dt, date_time_format)

model_file_name = f'LRCN_model__Date_Time_{current_date_time_string}__Loss_{model_evaluation_loss}__Accuracy_{model_evaluation_accuracy}.h5'

LRCN_model.save(model_file_name)

plot_metric(LRCN_model_training_history, 'loss', 'val_loss', 'Total Loss vs Total Validation Loss')

plot_metric(LRCN_model_training_history, 'accuracy', 'val_accuracy', 'Total Accuracy vs Total Validation Accuracy')

from google.colab import files
uploaded = files.upload()  # Manually upload your video file

input_video_file_path = list(uploaded.keys())[0]  # Get uploaded file name
print(f"Uploaded file: {input_video_file_path}")

def predict_on_video(video_file_path, output_file_path, SEQUENCE_LENGTH):
  video_reader = cv2.VideoCapture(video_file_path)
  original_video_width = int(video_reader.get(cv2.CAP_PROP_FRAME_WIDTH))
  original_video_height = int(video_reader.get(cv2.CAP_PROP_FRAME_HEIGHT))

  video_writer = cv2.VideoWriter(output_file_path, cv2.VideoWriter_fourcc('M', 'P', '4', 'V'), video_reader.get(cv2.CAP_PROP_FPS), (original_video_width, original_video_height))

  frame_queue = deque(maxlen = SEQUENCE_LENGTH)

  predicted_class_name = ''

  while video_reader.isOpened():

    ok, frame = video_reader.read()

    if not ok:
      break

    resized_frame = cv2.resize(frame, (IMAGE_HEIGHT, IMAGE_WIDTH))

    normalized_frame = resized_frame/255

    frame_queue.append(normalized_frame)

    if len(frame_queue) == SEQUENCE_LENGTH:

      predicted_labels_probabilities = LRCN_model.predict(np.expand_dims(frame_queue, axis =0 ))[0]

      predicted_label = np.argmax(predicted_labels_probabilities)

      predicted_class_name = CLASSES_LIST[predicted_label]

    cv2.putText(frame, predicted_class_name, (10,30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255,0), 2)

    video_writer.write(frame)

  video_reader.release()

  video_writer.release()

output_video_file_path = f"processed_{input_video_file_path}"

predict_on_video(input_video_file_path, output_video_file_path, SEQUENCE_LENGTH)

VideoFileClip(output_video_file_path, audio = False, target_resolution = (300, None)).ipython_display()

!pip install pafy youtube_dl yt-dlp

def predict_single_action(video_file_path, output_file_path, SEQUENCE_LENGTH):
  video_reader = cv2.VideoCapture(video_file_path)
  original_video_width = int(video_reader.get(cv2.CAP_PROP_FRAME_WIDTH))
  original_video_height = int(video_reader.get(cv2.CAP_PROP_FRAME_HEIGHT))

  frame_list = []

  predicted_class_name = ''

  video_frames_count = int(video_reader.get(cv2.CAP_PROP_FRAME_COUNT))

  skip_frames_window = max(int(video_frames_count/SEQUENCE_LENGTH), 1)

  for frame_counter in range(SEQUENCE_LENGTH):
    video_reader.set(cv2.CAP_PROP_POS_FRAMES, frame_counter*skip_frames_window)

    success, frame = video_reader.read()

    if not success:
      break

    resized_frame = cv2.resize(frame, (IMAGE_HEIGHT, IMAGE_WIDTH))

    normalized_frame = resized_frame/255

    frame_list.append(normalized_frame)

  predicted_labels_probabilities = LRCN_model.predict(np.expand_dims(frame_list, axis = 0))[0]

  predicted_label = np.argmax(predicted_labels_probabilities)

  predicted_class_name = CLASSES_LIST[predicted_label]

  print(f'Action Predicted: {predicted_class_name}\nConfidence: {predicted_labels_probabilities[predicted_label]}')

  video_reader.release()

video_file_path = f"processed_{input_video_file_path}"

predict_single_action(input_video_file_path, video_file_path, SEQUENCE_LENGTH)

VideoFileClip(video_file_path, audio = False, target_resolution = (300, None)).ipython_display()